export const INFLUENCER_TYPES = {
  ATHLETE: 'Athlete',
  FASHION: 'Fashion & Beauty',
  BEAUTY: 'Beauty',
  LIFESTYLE: 'Lifestyle',
  TECH: 'Tech & Gaming',
  GAMING: 'Gaming',
  FITNESS: 'Fitness & Wellness',
  FOOD: 'Food & Beverage',
  TRAVEL: 'Travel',
  BUSINESS: 'Business & Finance',
  ENTERTAINMENT: 'Entertainment',
  EDUCATION: 'Education',
  PARENTING: 'Parenting & Family',
  MUSIC: 'Music',
  ART: 'Art & Design',
  PHOTOGRAPHY: 'Photography',
  AUTOMOTIVE: 'Automotive',
  OUTDOOR: 'Outdoor & Adventure',
  PETS: 'Pets & Animals',
  SUSTAINABILITY: 'Sustainability',
  COMEDY: 'Comedy',
  HOME: 'Home & Design',
} as const;

export const ATHLETE_SPORTS = {
  FOOTBALL: 'Football',
  BASKETBALL: 'Basketball',
  BASEBALL: 'Baseball',
  SOCCER: 'Soccer',
  TENNIS: 'Tennis',
  GOLF: 'Golf',
  HOCKEY: 'Hockey',
  BOXING: 'Boxing',
  MMA: 'MMA',
  WRESTLING: 'Wrestling',
  TRACK_FIELD: 'Track & Field',
  SWIMMING: 'Swimming',
  GYMNASTICS: 'Gymnastics',
  VOLLEYBALL: 'Volleyball',
  CRICKET: 'Cricket',
  RUGBY: 'Rugby',
  SKIING: 'Skiing',
  SNOWBOARDING: 'Snowboarding',
  SURFING: 'Surfing',
  SKATEBOARDING: 'Skateboarding',
  CYCLING: 'Cycling',
  MOTORSPORTS: 'Motorsports',
  ESPORTS: 'Esports',
  CROSSFIT: 'CrossFit',
  BODYBUILDING: 'Bodybuilding',
} as const;

export const CONTENT_CATEGORIES = {
  FASHION: 'Fashion',
  BEAUTY: 'Beauty',
  MAKEUP: 'Makeup',
  SKINCARE: 'Skincare',
  LIFESTYLE: 'Lifestyle',
  VLOG: 'Vlog',
  TECH: 'Tech',
  GAMING: 'Gaming',
  FITNESS: 'Fitness',
  WELLNESS: 'Wellness',
  YOGA: 'Yoga',
  MEDITATION: 'Meditation',
  NUTRITION: 'Nutrition',
  FOOD: 'Food',
  COOKING: 'Cooking',
  BAKING: 'Baking',
  TRAVEL: 'Travel',
  ADVENTURE: 'Adventure',
  OUTDOOR: 'Outdoor',
  LUXURY: 'Luxury',
  BUSINESS: 'Business',
  FINANCE: 'Finance',
  INVESTING: 'Investing',
  ENTREPRENEURSHIP: 'Entrepreneurship',
  ENTERTAINMENT: 'Entertainment',
  COMEDY: 'Comedy',
  MUSIC: 'Music',
  DANCE: 'Dance',
  EDUCATION: 'Education',
  SCIENCE: 'Science',
  PARENTING: 'Parenting',
  FAMILY: 'Family',
  PETS: 'Pets',
  ART: 'Art',
  DESIGN: 'Design',
  PHOTOGRAPHY: 'Photography',
  AUTOMOTIVE: 'Automotive',
  REAL_ESTATE: 'Real Estate',
  HOME_DECOR: 'Home Decor',
  HOME: 'Home',
  DIY: 'DIY',
  SUSTAINABILITY: 'Sustainability',
  SPORTS: 'Sports',
} as const;

export const influencerTypesList = Object.values(INFLUENCER_TYPES);
export const athleteSportsList = Object.values(ATHLETE_SPORTS);
export const contentCategoriesList = Object.values(CONTENT_CATEGORIES);
