export const LOCATIONS = {
  US: {
    NEW_YORK: 'New York, NY',
    LOS_ANGELES: 'Los Angeles, CA',
    CHICAGO: 'Chicago, IL',
    HOUSTON: 'Houston, TX',
    PHOENIX: 'Phoenix, AZ',
    PHILADELPHIA: 'Philadelphia, PA',
    SAN_ANTONIO: 'San Antonio, TX',
    SAN_DIEGO: 'San Diego, CA',
    DALLAS: 'Dallas, TX',
    SAN_JOSE: 'San Jose, CA',
    AUSTIN: 'Austin, TX',
    JACKSONVILLE: 'Jacksonville, FL',
    FORT_WORTH: 'Fort Worth, TX',
    COLUMBUS: 'Columbus, OH',
    CHARLOTTE: 'Charlotte, NC',
    SAN_FRANCISCO: 'San Francisco, CA',
    INDIANAPOLIS: 'Indianapolis, IN',
    SEATTLE: 'Seattle, WA',
    DENVER: 'Denver, CO',
    BOSTON: 'Boston, MA',
    NASHVILLE: 'Nashville, TN',
    DETROIT: 'Detroit, MI',
    PORTLAND: 'Portland, OR',
    LAS_VEGAS: 'Las Vegas, NV',
    MIAMI: 'Miami, FL',
    ATLANTA: 'Atlanta, GA',
  },
  INTERNATIONAL: {
    LONDON: 'London, UK',
    PARIS: 'Paris, France',
    TOKYO: 'Tokyo, Japan',
    DUBAI: 'Dubai, UAE',
    SINGAPORE: 'Singapore',
    HONG_KONG: 'Hong Kong',
    SYDNEY: 'Sydney, Australia',
    TORONTO: 'Toronto, Canada',
    VANCOUVER: 'Vancouver, Canada',
    BERLIN: 'Berlin, Germany',
    AMSTERDAM: 'Amsterdam, Netherlands',
    BARCELONA: 'Barcelona, Spain',
    MADRID: 'Madrid, Spain',
    ROME: 'Rome, Italy',
    MILAN: 'Milan, Italy',
    MUMBAI: 'Mumbai, India',
    DELHI: 'Delhi, India',
    BANGALORE: 'Bangalore, India',
    SAO_PAULO: 'São Paulo, Brazil',
    MEXICO_CITY: 'Mexico City, Mexico',
    SEOUL: 'Seoul, South Korea',
    SHANGHAI: 'Shanghai, China',
    BEIJING: 'Beijing, China',
  },
} as const;

export const locationsList = [
  ...Object.values(LOCATIONS.US),
  ...Object.values(LOCATIONS.INTERNATIONAL),
].sort();
